name: ganns-with-friends
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - pillow>=9.0.0
  - pyyaml>=6.0
  - psycopg2>=2.9.0
  - pip
  - pip:
    - huggingface-hub>=0.20.0
